"""initial schema

Revision ID: 74686c0ba6bc
Revises: 
Create Date: 2026-09-13 21:41:26.064103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74686c0ba6bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'manager', 'team_member', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('deletion_reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('client',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('deletion_reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_type',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('deletion_reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('engagement',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('service_type_id', sa.UUID(), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=False),
    sa.Column('engagement_type', sa.Enum('one_time', 'recurring', name='engagement_type'), nullable=False),
    sa.Column('recurrence', sa.Enum('monthly', 'quarterly', 'annual', name='recurrence_frequency'), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('deletion_reason', sa.String(length=500), nullable=True),
    sa.CheckConstraint("(engagement_type = 'recurring' AND recurrence IS NOT NULL  AND period_start IS NOT NULL AND period_end IS NOT NULL) OR (engagement_type = 'one_time' AND recurrence IS NULL  AND period_start IS NULL AND period_end IS NULL)", name='engagement_recurring_has_period'),
    sa.CheckConstraint('period_start IS NULL OR period_end > period_start', name='engagement_period_ordered'),
    sa.CheckConstraint('period_start IS NULL OR start_date = period_start', name='engagement_start_matches_period'),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_type.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('engagement_unique_period', 'engagement', ['client_id', 'service_type_id', 'period_start'], unique=True, postgresql_where=sa.text('period_start IS NOT NULL AND deleted_at IS NULL'))
    op.create_table('task_template',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_type_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('default_offset_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('default_offset_days >= 0', name='task_template_offset_non_negative'),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_type.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_type_id', 'sequence', deferrable='True', initially='DEFERRED', name='task_template_sequence_unique')
    )
    op.create_table('task',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('engagement_id', sa.UUID(), nullable=False),
    sa.Column('task_template_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'assigned', 'in_progress', 'waiting_for_client', 'ready_for_review', 'changes_requested', 'completed', name='task_status'), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('deletion_reason', sa.String(length=500), nullable=True),
    sa.CheckConstraint('assignee_id IS NULL OR assignee_id <> reviewer_id', name='task_reviewer_is_not_assignee'),
    sa.ForeignKeyConstraint(['assignee_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['task_template_id'], ['task_template.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('task_assignee_status_idx', 'task', ['assignee_id', 'status'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('task_deleted_idx', 'task', ['deleted_at'], unique=False, postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.create_index('task_engagement_active_idx', 'task', ['engagement_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('task_review',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Enum('approved', 'changes_requested', 'reopened', name='review_decision'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision = 'approved' OR (comment IS NOT NULL AND length(btrim(comment)) > 0)", name='task_review_comment_required_when_negative'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('task_review_task_idx', 'task_review', ['task_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('task_review_task_idx', table_name='task_review')
    op.drop_table('task_review')
    op.drop_index('task_engagement_active_idx', table_name='task', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('task_deleted_idx', table_name='task', postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.drop_index('task_assignee_status_idx', table_name='task', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('task')
    op.drop_table('task_template')
    op.drop_index('engagement_unique_period', table_name='engagement', postgresql_where=sa.text('period_start IS NOT NULL AND deleted_at IS NULL'))
    op.drop_table('engagement')
    op.drop_table('service_type')
    op.drop_table('client')
    op.drop_table('app_user')
    # ### end Alembic commands ###
    sa.Enum(name='review_decision').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='task_status').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='recurrence_frequency').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='engagement_type').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='user_role').drop(op.get_bind(), checkfirst=False)
